name: core
description: "core package"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #network
  dio: ^5.8.0+1

  #json
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0

  #firebase
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_remote_config: ^5.4.4

  #storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  #notification
  flutter_local_notifications: ^19.0.0

  #system info
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0

  #system path
  path_provider: ^2.1.5

  #dependencies
  get_it: ^8.0.3
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  test: ^1.25.8
  build_runner: ^2.4.15