name: front
description: "국회의원 정보 및 발의 법안 정보 제공 프로젝트"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+11

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  features:
    path: ../features
  core:
    path: ../core

  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.0.0

  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

  #dependencies
  get_it: ^8.0.3
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  test: ^1.25.8
  build_runner: ^2.4.15
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app/
    - assets/pictures/
  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSansTTFBold.ttf
          weight: 700
        - asset: assets/fonts/GmarketSansTTFLight.ttf
          weight: 300
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
          weight: 500

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app/app_icon_logo_바로.png"