name: features
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #package dependencies
  common:
    path: ../common
  core:
    path: ../core
  design_system:
    path: ../design_system

  #external dependencies
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.3
  intl: ^0.20.2
  shimmer: ^3.0.0
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.0.0
  webview_flutter: ^4.11.0
  cached_network_image: ^3.4.1
  screenshot: ^3.0.0
  uuid: ^4.5.1
  pub_semver: ^2.2.0
  go_router: ^14.8.1
  share_plus: ^10.1.4
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.6.2
