name: design_system
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0